import Foundation

/// One album as offered to the picker sheet.
///
/// The iOS layer builds these from `PHAssetCollection`; this type carries only
/// what the ordering and filtering rules need, so those rules stay testable
/// without a photo library.
public struct AlbumCandidate: Equatable, Sendable, Identifiable {
    public let id: AlbumID
    public let title: String

    /// Smart albums (Recents, Favourites, Screenshots) are generated by the
    /// system and cannot be added to.
    public let isSmartAlbum: Bool

    /// Mirrors `PHAssetCollection.canPerform(.addContent)`. Even a regular user
    /// album can refuse additions — a shared album you do not own, for instance.
    public let canAddContent: Bool

    public init(id: AlbumID, title: String, isSmartAlbum: Bool, canAddContent: Bool) {
        self.id = id
        self.title = title
        self.isSmartAlbum = isSmartAlbum
        self.canAddContent = canAddContent
    }
}

/// Decides which albums the picker offers, and in what order.
public enum AlbumPicker {

    /// Albums that can actually accept a photo.
    ///
    /// Offering an album that will reject the write is worse than hiding it: the
    /// tap appears to succeed and the photo silently never arrives.
    public static func selectable(from candidates: [AlbumCandidate]) -> [AlbumCandidate] {
        candidates.filter { !$0.isSmartAlbum && $0.canAddContent }
    }

    /// Selectable albums, most-recently-filed-into first, then the rest by title.
    ///
    /// In practice a few albums absorb almost everything, so pinning recents is
    /// the difference between one tap and a scroll on every single photo.
    ///
    /// - Parameters:
    ///   - candidates: every album fetched from the library.
    ///   - recentlyUsed: album ids most-recent-first. Ids that are no longer
    ///     selectable (deleted album, permissions changed) are ignored.
    public static func ordered(
        from candidates: [AlbumCandidate],
        recentlyUsed: [AlbumID]
    ) -> [AlbumCandidate] {
        let selectable = selectable(from: candidates)
        let byID = Dictionary(uniqueKeysWithValues: selectable.map { ($0.id, $0) })

        var pinned: [AlbumCandidate] = []
        var pinnedIDs = Set<AlbumID>()
        for id in recentlyUsed {
            guard let album = byID[id], pinnedIDs.insert(id).inserted else { continue }
            pinned.append(album)
        }

        let rest = selectable
            .filter { !pinnedIDs.contains($0.id) }
            .sorted { $0.title.localizedCaseInsensitiveCompare($1.title) == .orderedAscending }

        return pinned + rest
    }

    /// Records `album` as the most recently used, keeping the list capped.
    ///
    /// Re-filing into an album already in the list moves it to the front rather
    /// than adding a duplicate.
    public static func recordUse(
        of album: AlbumID,
        in recentlyUsed: [AlbumID],
        limit: Int = 4
    ) -> [AlbumID] {
        guard limit > 0 else { return [] }
        var updated = recentlyUsed.filter { $0 != album }
        updated.insert(album, at: 0)
        return Array(updated.prefix(limit))
    }
}
